### ISSUE TITLE
Error: 'output.filename' is required, either in config file or as --output-filename

### ISSUE THREAD

**Issue by rafis** [kjbekkelund/generate-asset-webpack-plugin#1]
How to only generate file using your plugin with main output file?

```javascript
module.exports = {
    plugins: [
        new GenerateAssetPlugin({
            filename: 'index.html',
            fn: (compilation, cb) => {
                cb(null, createHtml(compilation));
            }
        })
    ]
};
```

**Comment by kimjoar** [comment]
Hi, sorry, haven't used this plugin in a long time myself (I use https://github.com/jantimon/html-webpack-plugin instead). I recommend checking that out, it's better maintained and has more docs.

**Comment by rafis** [comment]
The question was a bit different. I wanted to generate file without specifying `entry` and `output.filename` in webpack.config.js. This is because I was thinking withing ideology of Gulp, but Webpack is [different ideology](https://webpack.github.io/docs/loaders.html) and now I understand how to generate files. I need to use [apply-loader](https://github.com/mogelbrod/apply-loader).
